// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9od_bVrTYA9UU78niAKKB85jeO1qRKJ0',
    appId: '1:405686073871:web:c97d9dfbe7a3e8944f417a',
    messagingSenderId: '405686073871',
    projectId: 'user-app-firebase-a9e59',
    authDomain: 'user-app-firebase-a9e59.firebaseapp.com',
    storageBucket: 'user-app-firebase-a9e59.appspot.com',
    measurementId: 'G-LM8P1WN8TX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3CXlg6tF5gt2VWyHH5EPt_RFnNDXI9_o',
    appId: '1:405686073871:android:57062711b6a6e8d84f417a',
    messagingSenderId: '405686073871',
    projectId: 'user-app-firebase-a9e59',
    storageBucket: 'user-app-firebase-a9e59.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBX9-qcEoWtcZ_Nvj0HMTPvbwaBHYw3uXA',
    appId: '1:405686073871:ios:de3b03869ad04a024f417a',
    messagingSenderId: '405686073871',
    projectId: 'user-app-firebase-a9e59',
    storageBucket: 'user-app-firebase-a9e59.appspot.com',
    iosBundleId: 'com.app.lemine.userApp',
  );
}
